-- Enable UUID extension if needed (good practice, but we use integer IDs in code)
-- create extension if not exists "uuid-ossp";

-- 1. Users Table
create table users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text not null,
  role text default 'user',
  last_login timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Subjects Table
create table subjects (
  id bigint generated by default as identity primary key,
  name_ar text not null,
  name_en text not null,
  code text unique not null,
  description_ar text,
  description_en text,
  semester int default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Statistics Table
create table statistics (
  id bigint generated by default as identity primary key,
  subject_id bigint references subjects(id) on delete cascade,
  total_lectures int default 0,
  total_sheets int default 0,
  total_assignments int default 0,
  total_exams int default 0,
  total_references int default 0,
  total_questions int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Resources Table (Includes Lectures, Assignments, Sheets, etc.)
create table resources (
  id bigint generated by default as identity primary key,
  subject_id bigint references subjects(id) on delete cascade,
  type text not null,
  title_ar text not null,
  title_en text not null,
  description_ar text,
  description_en text,
  file_path text,
  file_url text, -- Public URL
  file_size bigint,
  file_type text,
  source text,
  added_by bigint references users(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Announcements Table
create table announcements (
  id bigint generated by default as identity primary key,
  title_ar text not null,
  title_en text not null,
  content_ar text not null,
  content_en text not null,
  priority text default 'medium',
  type text default 'general',
  is_active boolean default true,
  added_by bigint references users(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Questions Table
create table questions (
  id bigint generated by default as identity primary key,
  subject_id bigint references subjects(id) on delete cascade,
  topic_ar text,
  topic_en text,
  question_text_ar text,
  question_text_en text,
  answer_text_ar text,
  answer_text_en text,
  image_path text,
  difficulty text default 'medium',
  added_by bigint references users(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Storage Buckets Setup (Run correctly in SQL Editor or via Dashboard)
insert into storage.buckets (id, name, public) 
values ('uploads', 'uploads', true)
on conflict (id) do nothing;

-- Storage Policies (Make public access allowed)
create policy "Public Access" on storage.objects for select using ( bucket_id = 'uploads' );
create policy "Authenticated Upload" on storage.objects for insert with check ( bucket_id = 'uploads' );
